# Enable the H2 Console so you can see your data in the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Set a fixed database name (so the link doesn't change every time you restart)
spring.datasource.url=jdbc:h2:mem:bankdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Show the SQL queries in the console (Great for debugging!)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update